name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  direct:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/upload-artifact@v3

  indirect:
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.0.0
    with:
      extension_name: something
      duckdb_version: v1.1.2
